version: 1

formatters:
  main:
    format: "%(asctime)s %(name)s %(levelname)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: main

  file_handler:
    class: logging.FileHandler
    level: DEBUG
    filename: data.log
    formatter: main

loggers:
  data_flow:
    level: DEBUG
    handlers: [console, file_handler]
root:
  handlers: []